---
# Template de Ansible Playbook para Hardening Linux
# Basado en CIS Benchmarks y mejores pr치cticas 2025
# Uso: ansible-playbook -i inventory template-ansible-hardening.yml

- name: System Hardening Playbook
  hosts: all
  become: yes
  vars:
    # Configuraci칩n de firewall
    firewall_allowed_ports:
      - port: "22"
        proto: "tcp"
        name: "SSH"
      - port: "80"
        proto: "tcp"
        name: "HTTP"
      - port: "443"
        proto: "tcp"
        name: "HTTPS"
    
    # Configuraci칩n de usuarios
    disable_root_login: true
    require_ssh_key: true
    
    # Configuraci칩n de servicios
    services_to_disable:
      - bluetooth
      - cups
      - avahi-daemon
    
  tasks:
    - name: Update system packages
      package:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
    
    - name: Install security updates
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"
    
    - name: Install UFW
      package:
        name: ufw
        state: present
    
    - name: Configure UFW default policies
      ufw:
        state: enabled
        policy: "{{ item.policy }}"
        direction: "{{ item.direction }}"
      loop:
        - { policy: "deny", direction: "incoming" }
        - { policy: "allow", direction: "outgoing" }
    
    - name: Allow specific ports in UFW
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: "{{ firewall_allowed_ports }}"
    
    - name: Disable root login in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        backup: yes
      notify: restart sshd
      when: disable_root_login
    
    - name: Disable password authentication in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        backup: yes
      notify: restart sshd
      when: require_ssh_key
    
    - name: Disable unnecessary services
      systemd:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop: "{{ services_to_disable }}"
    
    - name: Configure kernel parameters
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { key: "net.ipv4.ip_forward", value: "0" }
        - { key: "net.ipv4.tcp_syncookies", value: "1" }
        - { key: "net.ipv4.conf.all.accept_redirects", value: "0" }
        - { key: "net.ipv4.conf.default.accept_redirects", value: "0" }
        - { key: "net.ipv4.conf.all.send_redirects", value: "0" }
        - { key: "net.ipv4.conf.default.send_redirects", value: "0" }
    
    - name: Install fail2ban
      package:
        name: fail2ban
        state: present
    
    - name: Enable and start fail2ban
      systemd:
        name: fail2ban
        enabled: yes
        state: started
    
    - name: Install unattended-upgrades
      package:
        name: unattended-upgrades
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Configure automatic security updates
      debconf:
        name: unattended-upgrades
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        - { question: "unattended-upgrades/enable_auto_updates", value: "true", vtype: "boolean" }
      when: ansible_os_family == "Debian"
  
  handlers:
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted
